name: Run Selenium TestNG Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build & Run TestNG Tests
        run: mvn clean test

      - name: Upload TestNG Reports
        if: always()
        uses: actions/upload-artifact@v4   # 👈 new version
        with:
          name: testng-reports
          path: test-output   # or target/surefire-reports if using Maven Surefire
